[package]
name = "integration_tests"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
lee = { workspace = true }
lee_core = { workspace = true, features = ["host", "test_utils"] }
clock_core = { git = "https://github.com/logos-blockchain/logos-execution-zone.git", tag = "v0.2.4" }
amm_core = { workspace = true }
token_core = { workspace = true }
ata_core = { workspace = true }
stablecoin_core = { workspace = true }
twap_oracle_core = { workspace = true }
vesting_core = { path = "../vesting/core" }
token-methods = { path = "../token/methods" }
amm-methods = { path = "../amm/methods" }
ata-methods = { path = "../ata/methods" }
stablecoin-methods = { path = "../stablecoin/methods" }
twap-oracle-methods = { path = "../twap_oracle/methods" }
vesting-methods = { path = "../vesting/methods" }
