[package]
name = "vesting-methods"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[lints]
workspace = true

[build-dependencies]
risc0-build = "=3.0.5"

[dependencies]
risc0-zkvm = { version = "=3.0.5", features = ["std"] }
vesting_core = { path = "../core" }

[package.metadata.risc0]
methods = ["guest"]
